### ISSUE TITLE
How can upgrade firmware?

### ISSUE THREAD

**Issue by gazambuja** [anandtamboli/1btn#5]
How is the easy step to upgrade official firmware?

**Comment by knewron-technologies** [comment]
If you want to change firmware files on the module, simply stop the button from entering into the main program by stopping timer 0 when triggered.

However, if you want to wipe out base firmware and re-write whole thing, you'll have to connect b0 point to the ground while resetting the device. This will take it into boot mode and you can upgrade it with the new firmware.

**Comment by experimental-tinker-dude** [comment]
Hey, this may sound stupid, but could you please be a bit more specific about pin b0?
I cannot find it on the board, neither on the schematics/layouts under the folder "pcb" in the repo.
I'm desperately trying to flash the firmware of 1btn for hours. The documentation is not really helpful. :(

**Comment by knewron-technologies** [comment]
Pls send in your purchase details and email id to communicate further.

From
KNEWRON Technologies


On 13-Jul-2017 5:02 AM, "experimental-tinker-dude" <notifications@github.com>
wrote:

Hey, this may sound stupid, but could you please be a bit more specific
about pin b0?
I cannot find it on the board, neither on the schematics/layouts under the
folder "pcb" in the repo.
I'm desperately trying to flash the firmware of 1btn for hours. The
documentation is not really helpful. :(

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/knewron-technologies/1btn/issues/5#issuecomment-314865763>,
or mute the thread
